token:         # Lichess OAuth2 Token.

engines:
  standard:
    dir: "./engines/"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 7
      Hash: 4096
      Move Overhead: 250
    limits:
      time: 5.0
      depth: 26
      nodes: 4000000

  chess960:
    dir: "./engines/"
    name: "stockfish"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 7
      Hash: 4096
      Move Overhead: 250
    limits:
      time: 5.0
      depth: 26
      nodes: 4000000

syzygy:
  standard:
    enabled: false
    paths:
      - "/path/to/standard/syzygy"
    max_pieces: 7
    instant_play: true
  antichess:
    enabled: false
    paths:
      - "/path/to/antichess/syzygy"
    max_pieces: 6
    instant_play: true
  atomic:
    enabled: false
    paths:
      - "/path/to/atomic/syzygy"
    max_pieces: 6
    instant_play: true

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

opening_books:
  enabled: true
  priority: 400
  books:
    default:
      names:
        - DefaultBook
        - BackupBook
    standard_black:
      selection: weighted_random
#     max_depth: 6
      names:
        - BlackBook

online_moves:
  opening_explorer:
    enabled: false
    priority: 300
    only_without_book: false
    use_for_variants: false
    min_time: 10
    timeout: 5
    min_games: 5
    only_with_wins: false
    selection: "performance"
    anti: false
#   max_depth: 16
#   max_moves: 1
  lichess_cloud:
    enabled: false
    priority: 200
    only_without_book: false
    use_for_variants: true
    min_eval_depth: 10
    min_time: 10
    timeout: 5
#   max_depth: 16
#   max_moves: 1
  chessdb:
    enabled: true
    priority: 100
    only_without_book: false
    min_candidates: 1
    min_time: 10
    timeout: 5
    selection: "good"
#   max_depth: 16
#   max_moves: 1
  online_egtb:
    enabled: true
    min_time: 20
    timeout: 3

offer_draw:
  enabled: true
  score: 10
  consecutive_moves: 5
  min_game_length: 25
  against_humans: false

resign:
  enabled: true
  score: -1000
  consecutive_moves: 5
  against_humans: false

challenge:
  concurrency: 2
  max_takebacks: 5
  bullet_with_increment_only: false
# min_increment: 0
# max_increment: 180
# min_initial: 0
# max_initial: 315360000
  variants:
    - standard
    - chess960
#   - fromPosition
#   - antichess
#   - atomic
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:
    - bullet
    - blitz
    - rapid
#   - classical
#   - 25+0
  bot_modes:
    - casual
    - rated
  human_modes:
    - casual
    - rated

matchmaking:
  delay: 0
  timeout: 5
  selection: weighted_random
  types:
    bullet:
      tc: 0.5+0
#   casual_chess960:
#     tc: 0.5+1
#     rated: false
#     variant: chess960
#   optional_settings:
#     rated: true
#     variant: standard
#     weight: 100
#     multiplier: 15
#     min_rating_diff: 0
#     max_rating_diff: 300

messages:
  greeting: "Hi! I'm {me} running {engine}. Good Luck!"
  goodbye: "Good Game!"
  greeting_spectators: "Hi! I'm {me} running {engine}. I hope you enjoy the game!"
  goodbye_spectators: "Good Bye!"

whitelist:
# - Username1
# - Username2

blacklist:
# - Username1
# - Username2

books:
  DefaultBook: "./engines/Book2.bin"
  BackupBook: "./engines/Book3.bin"
  BlackBook: "./engines/black.bin"
